"""Update QuEra key_people with enriched profiles from web search."""
import json, sqlite3

key_people = [
    {
        "name": "Mikhail Lukin",
        "title": "联合创始人 & 首席科学家",
        "linkedin": "",
        "google_scholar": "https://scholar.google.com/citations?user=ppJpl64AAAAJ",
        "academic_background": {"highest_degree": "PhD", "field": "物理学",
            "institutions": ["Harvard University", "Texas A&M University", "Moscow Institute of Physics and Technology"],
            "graduation_year": "1998"},
        "previous_experience": [
            {"company": "Harvard University", "role": "物理学教授", "period": "2004-至今"},
            {"company": "Harvard Quantum Initiative", "role": "联合主任", "period": "2018-至今"},
            {"company": "Harvard-Smithsonian Center for Astrophysics", "role": "博士后", "period": "1998-2001"},
        ],
        "research_focus": ["中性原子量子计算", "里德伯原子阵列", "量子纠错", "量子模拟", "金刚石NV色心量子传感"],
        "publications_highlights": [
            "Nature (2023): Logical quantum processor based on reconfigurable atom arrays — 1,689引用",
            "Nature (2025): Low-Overhead Transversal Fault Tolerance",
            "Science (2021): Probing topological spin liquids on a programmable quantum simulator — 1,423引用",
            "Nature (2023): High-fidelity parallel entangling gates on a neutral-atom quantum computer",
        ],
        "h_index_estimate": 176,
        "notable_achievements": [
            "美国国家科学院院士 (2018)",
            "I. I. Rabi Prize (APS, 2009) — 原子分子光学物理最高荣誉",
            "450+ 论文, 136,000+ 引用",
            "中性原子量子计算路线奠基人，QuEra 核心技术发明人",
        ],
        "role_at_algorithmiq": "联合创始人 & 首席科学家",
    },
    {
        "name": "Andy Ory",
        "title": "首席执行官 (CEO)",
        "linkedin": "",
        "academic_background": {"highest_degree": "MBA", "field": "",
            "institutions": ["Harvard Business School"], "graduation_year": ""},
        "previous_experience": [
            {"company": "Acme Packet", "role": "CEO 兼联合创始人", "period": "2000-2013 (被 Oracle 以 21亿美元收购)"},
            {"company": "QuEra Computing", "role": "CEO", "period": "2023-至今"},
        ],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "带领 Acme Packet 从零到 IPO，最终被 Oracle 以 21亿美元收购",
            "为 QuEra 争取到 Google/软银领投的 2.3亿美元战略融资",
            "多家企业科技公司董事会成员",
        ],
        "role_at_algorithmiq": "CEO",
    },
    {
        "name": "Alex Keesling",
        "title": "前 CEO / QuEra UK 董事",
        "linkedin": "",
        "academic_background": {"highest_degree": "PhD", "field": "物理学",
            "institutions": ["Harvard University"], "graduation_year": ""},
        "previous_experience": [
            {"company": "QuEra Computing", "role": "CEO (创始CEO)", "period": "2018-2023"},
            {"company": "QuEra Computing UK Limited", "role": "董事", "period": "2023-至今"},
        ],
        "research_focus": ["中性原子量子计算", "量子硬件工程"],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "QuEra 创始 CEO，带领公司从哈佛实验室走向商业化",
            "主导 Aquila 256-qubit 量子计算机的开发和发布",
        ],
        "role_at_algorithmiq": "创始 CEO",
    },
    {
        "name": "Vladan Vuletić",
        "title": "联合创始人 & CTO",
        "linkedin": "https://www.linkedin.com/in/vladan-vuletic-22332545/",
        "google_scholar": "https://scholar.google.com/citations?user=E_7YsOgAAAAJ",
        "academic_background": {"highest_degree": "PhD", "field": "物理学",
            "institutions": ["MIT", "Ludwig-Maximilians-Universität München", "Stanford University (博士后)"],
            "graduation_year": "1997"},
        "previous_experience": [
            {"company": "MIT", "role": "Lester Wolfe 物理学教授", "period": "2003-至今"},
            {"company": "Stanford University", "role": "助理教授", "period": "2000-2003"},
            {"company": "Steven Chu 实验室 (Stanford)", "role": "博士后", "period": "1997-2000"},
        ],
        "research_focus": ["冷原子与激光冷却", "里德伯原子阵列量子模拟", "量子计量", "腔QED", "自旋压缩与纠缠"],
        "publications_highlights": [
            "Nature (2017): Probing many-body dynamics on a 51-atom quantum simulator — 3,190引用",
            "Nature (2024): Logical quantum processor based on reconfigurable atom arrays — 1,689引用",
            "Nature (2021): Quantum phases of matter on a 256-atom programmable simulator — 1,423引用",
        ],
        "h_index_estimate": 65,
        "notable_achievements": [
            "MIT Lester Wolfe 物理学教授",
            "美国物理学会会士 (2012), AAAS 会士 (2023)",
            "Web of Science 高被引学者 (2022)",
            "236 篇论文, 20,000+ 引用",
        ],
        "role_at_algorithmiq": "联合创始人 & CTO",
    },
    {
        "name": "Markus Greiner",
        "title": "联合创始人",
        "linkedin": "",
        "academic_background": {"highest_degree": "PhD", "field": "物理学",
            "institutions": ["Harvard University", "Ludwig-Maximilians-Universität München"], "graduation_year": ""},
        "previous_experience": [
            {"company": "Harvard University", "role": "物理学教授", "period": "2012-至今"},
        ],
        "research_focus": ["量子模拟", "光晶格", "超冷原子", "多体局域化", "量子相变"],
        "publications_highlights": [
            "Nature (2017): Many-body localization with ultracold atoms",
            "Science (2016): Atom-by-atom assembly of defect-free cold atom arrays — 1,177引用",
        ],
        "h_index_estimate": 55,
        "notable_achievements": [
            "光晶格单原子分辨成像技术先驱",
            "麦克阿瑟天才奖获得者",
            "137 篇论文, 28,000+ 引用",
        ],
        "role_at_algorithmiq": "联合创始人",
    },
    {
        "name": "Dirk Englund",
        "title": "联合创始人",
        "linkedin": "https://www.linkedin.com/in/dirk-englund-263aa02/",
        "academic_background": {"highest_degree": "PhD", "field": "电子工程/应用物理",
            "institutions": ["MIT", "Stanford University", "Caltech", "Harvard University (博士后)"],
            "graduation_year": "2008"},
        "previous_experience": [
            {"company": "MIT", "role": "EECS 教授", "period": "2013-至今"},
            {"company": "Columbia University", "role": "助理教授", "period": "2010-2013"},
            {"company": "Harvard University (Lukin 组)", "role": "博士后", "period": "2008-2010"},
        ],
        "research_focus": ["量子光子学", "集成量子系统", "金刚石色心量子存储器", "光子AI加速器", "量子网络"],
        "publications_highlights": [],
        "h_index_estimate": 81,
        "notable_achievements": [
            "Humboldt 教授奖获得者",
            "Optica Adolph Lomb 奖章获得者",
            "Optica 会士",
            "同时创办 Lightmatter (光子AI芯片, 估值数十亿) 和 DUST Identity (金刚石防伪)",
            "725 篇论文, 33,000+ 引用",
        ],
        "role_at_algorithmiq": "联合创始人",
    },
    {
        "name": "Nathan Gemelke",
        "title": "联合创始人 & 首席技术战略官",
        "linkedin": "https://www.linkedin.com/in/nate-gemelke-885025154/",
        "academic_background": {"highest_degree": "PhD", "field": "物理学",
            "institutions": ["Harvard University"], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": ["容错量子计算架构", "横向门 (Transversal Gates)", "中性原子量子硬件"],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "Transversal STAR 容错架构设计者",
            "技术路线图: 2028年实现 1000+ 逻辑量子比特, 保真度 99.9999999%",
        ],
        "role_at_algorithmiq": "CTO",
    },
    {
        "name": "Takuya Kitagawa",
        "title": "总裁 (President)",
        "linkedin": "https://www.linkedin.com/in/takuya-kitagawa-2b366117/",
        "academic_background": {"highest_degree": "PhD", "field": "物理学",
            "institutions": ["University of Tokyo", "Harvard University"], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "主导 2.3亿美元 Google/软银战略融资",
            "争取到日本 AIST 4100万美元国家级量子部署合同",
            "公司董事会成员",
        ],
        "role_at_algorithmiq": "总裁",
    },
    {
        "name": "Yuval Boger",
        "title": "首席商务官 (CCO)",
        "linkedin": "https://www.linkedin.com/in/yuvalboger/",
        "academic_background": {"highest_degree": "MBA", "field": "",
            "institutions": [], "graduation_year": ""},
        "previous_experience": [
            {"company": "Classiq Technologies", "role": "首席营销官 (CMO)", "period": "2020-2024"},
        ],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "量子计算行业资深专家, 20+年经验",
            "主持知名量子计算播客 'The Superposition Guy'",
        ],
        "role_at_algorithmiq": "CCO",
    },
    {
        "name": "Ed Durkin",
        "title": "首席财务官 (CFO) / QuEra UK 董事",
        "linkedin": "https://www.linkedin.com/in/ed-durkin-36362a24/",
        "academic_background": {"highest_degree": "MBA", "field": "金融",
            "institutions": [], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "管理公司快速成长期的财务运营和投资者关系",
            "兼任 QuEra UK Limited 董事 (2025年3月起)",
        ],
        "role_at_algorithmiq": "CFO",
    },
    {
        "name": "Dean Bogdanovic",
        "title": "工程高级副总裁 (SVP Engineering)",
        "linkedin": "https://www.linkedin.com/in/dbogdanovic/",
        "academic_background": {"highest_degree": "硕士/博士", "field": "计算机科学/工程",
            "institutions": [], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": ["量子控制系统", "经典-量子接口", "实时量子纠错"],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "负责中性原子量子计算机的经典控制系统全栈工程",
        ],
        "role_at_algorithmiq": "SVP Engineering",
    },
    {
        "name": "Steve Suarez",
        "title": "前 UK 企业董事 (2024.1-2025.2)",
        "linkedin": "",
        "academic_background": {"highest_degree": "", "field": "",
            "institutions": [], "graduation_year": ""},
        "previous_experience": [
            {"company": "HSBC", "role": "全球创新主管 (Global Head of Innovation)", "period": ""},
            {"company": "HorizonX Consulting", "role": "CEO", "period": ""},
            {"company": "QuEra Computing UK", "role": "企业董事", "period": "2024.1-2025.2"},
        ],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "前 HSBC 全球创新主管",
            "双国籍(美/英), 驻地迪拜",
            "负责 QuEra 在英国的早期战略拓展",
        ],
        "role_at_algorithmiq": "前 UK 董事",
    },
    {
        "name": "Arthur Chu",
        "title": "董事会成员",
        "linkedin": "",
        "academic_background": {"highest_degree": "", "field": "",
            "institutions": [], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["QuEra Computing Inc. 董事会成员"],
        "role_at_algorithmiq": "Board Member",
    },
    {
        "name": "Paul Maritz",
        "title": "董事会成员",
        "linkedin": "",
        "academic_background": {"highest_degree": "", "field": "",
            "institutions": [], "graduation_year": ""},
        "previous_experience": [
            {"company": "VMware", "role": "CEO", "period": "2008-2012"},
            {"company": "Pivotal Software", "role": "CEO", "period": "2013-2015"},
            {"company": "Microsoft", "role": "高级副总裁", "period": "1986-2000"},
        ],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": [
            "VMware 前 CEO (2008-2012)",
            "Microsoft 早期高管 (1986-2000), 领导 Windows 95 和 Internet Explorer 开发",
            "Pivotal Software 创始人兼 CEO",
            "硅谷传奇人物, 企业软件领域顶级战略家",
        ],
        "role_at_algorithmiq": "Board Member",
    },
]

conn = sqlite3.connect("profiles.db")
conn.execute("UPDATE competitor_profiles SET key_people=? WHERE id=2",
             (json.dumps(key_people, ensure_ascii=False),))

# Also update team_analytics
team_analytics = {
    "total_researched": 14,
    "avg_h_index": 65,
    "top_institutions": {"Harvard University": 5, "MIT": 3, "Stanford University": 2},
    "degree_distribution": {"PhD": 10, "MBA": 3, "硕士/博士": 1},
    "career_stages": {
        "教授/学术领袖": 4,
        "高管/连续创业者": 5,
        "VP/总监级别": 3,
        "董事会成员": 2,
    },
    "h_index_range": [0, 176],
}
conn.execute("UPDATE competitor_profiles SET team_analytics=? WHERE id=2",
             (json.dumps(team_analytics, ensure_ascii=False),))
conn.commit()
conn.close()
print(f"Updated {len(key_people)} people + team_analytics")
