"""Update QuEra key_people with structured profiles matching Algorithmiq format."""
import json, sqlite3

key_people = [
    {
        "name": "Mikhail Lukin",
        "title": "Co-Founder & Chief Scientist",
        "linkedin": "",
        "academic_background": {"highest_degree": "PhD", "field": "Physics", "institutions": ["Harvard University", "Moscow Institute of Physics and Technology"], "graduation_year": "1998"},
        "previous_experience": [{"company": "Harvard University", "role": "Professor of Physics", "period": "2001-present"}, {"company": "Harvard Quantum Initiative", "role": "Co-Director", "period": "2018-present"}],
        "research_focus": ["Neutral Atom Quantum Computing", "Quantum Error Correction", "Rydberg Atom Arrays"],
        "publications_highlights": ["Nature (2025): Low-Overhead Transversal Fault Tolerance", "Nature (2023): Logical Quantum Processor on Reconfigurable Atom Arrays"],
        "h_index_estimate": 80,
        "notable_achievements": ["Member, US National Academy of Sciences", "Pioneer of neutral atom quantum computing", "500+ publications, 80,000+ citations"],
        "role_at_algorithmiq": "Co-Founder & Chief Scientist",
    },
    {
        "name": "Andy Ory",
        "title": "CEO",
        "linkedin": "",
        "academic_background": {"highest_degree": "MBA", "field": "", "institutions": ["Harvard Business School"], "graduation_year": ""},
        "previous_experience": [{"company": "Acme Packet", "role": "CEO & Co-Founder", "period": "2000-2013 (acquired by Oracle for $2.1B)"}],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["Led Acme Packet to $2.1B Oracle acquisition", "Secured $230M strategic round from Google and SoftBank"],
        "role_at_algorithmiq": "CEO",
    },
    {
        "name": "Nathan Gemelke",
        "title": "Co-Founder & Chief Technology Strategist",
        "linkedin": "https://www.linkedin.com/in/nate-gemelke-885025154/",
        "academic_background": {"highest_degree": "PhD", "field": "Physics", "institutions": ["Harvard University"], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": ["Fault-Tolerant Architecture", "Transversal Gates", "Quantum Hardware"],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["Architect of Transversal STAR FTQC architecture", "Technology roadmap: 1000+ logical qubits by 2028"],
        "role_at_algorithmiq": "CTO",
    },
    {
        "name": "Vladan Vuletic",
        "title": "Co-Founder",
        "linkedin": "https://www.linkedin.com/in/vladan-vuletic-22332545/",
        "academic_background": {"highest_degree": "PhD", "field": "Physics", "institutions": ["MIT"], "graduation_year": ""},
        "previous_experience": [{"company": "MIT", "role": "Professor of Physics", "period": "2000-present"}],
        "research_focus": ["Cavity QED", "Cold Atoms", "Quantum Metrology"],
        "publications_highlights": ["Nature Physics: Constant-Overhead FTQC"],
        "h_index_estimate": 60,
        "notable_achievements": ["MIT Physics Professor", "Pioneer in cavity QED with neutral atoms"],
        "role_at_algorithmiq": "Co-Founder",
    },
    {
        "name": "Markus Greiner",
        "title": "Co-Founder",
        "linkedin": "",
        "academic_background": {"highest_degree": "PhD", "field": "Physics", "institutions": ["Harvard University"], "graduation_year": ""},
        "previous_experience": [{"company": "Harvard University", "role": "Professor of Physics", "period": "2012-present"}],
        "research_focus": ["Quantum Simulation", "Optical Lattices", "Ultracold Atoms"],
        "publications_highlights": ["Nature: Many-body localization with ultracold atoms"],
        "h_index_estimate": 55,
        "notable_achievements": ["Single-atom resolved imaging in optical lattices", "MacArthur Fellowship recipient"],
        "role_at_algorithmiq": "Co-Founder",
    },
    {
        "name": "Dirk Englund",
        "title": "Co-Founder",
        "linkedin": "https://www.linkedin.com/in/dirk-englund-263aa02/",
        "academic_background": {"highest_degree": "PhD", "field": "Electrical Engineering", "institutions": ["MIT", "Stanford University"], "graduation_year": ""},
        "previous_experience": [{"company": "MIT", "role": "Professor of EECS", "period": "2013-present"}],
        "research_focus": ["Quantum Photonics", "Integrated Quantum Systems", "Diamond NV Centers"],
        "publications_highlights": [],
        "h_index_estimate": 50,
        "notable_achievements": ["MIT EECS Professor", "Leader in quantum photonic integrated circuits"],
        "role_at_algorithmiq": "Co-Founder",
    },
    {
        "name": "Takuya Kitagawa",
        "title": "President",
        "linkedin": "https://www.linkedin.com/in/takuya-kitagawa-2b366117/",
        "academic_background": {"highest_degree": "PhD", "field": "Physics", "institutions": ["University of Tokyo", "Harvard University"], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["Led $230M strategic fundraising", "Secured Japan AIST $41M contract"],
        "role_at_algorithmiq": "President",
    },
    {
        "name": "Yuval Boger",
        "title": "Chief Commercial Officer",
        "linkedin": "https://www.linkedin.com/in/yuvalboger/",
        "academic_background": {"highest_degree": "MBA", "field": "", "institutions": [], "graduation_year": ""},
        "previous_experience": [{"company": "Classiq Technologies", "role": "CMO", "period": "2020-2024"}],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["Quantum computing industry veteran", "Hosts popular quantum computing podcast"],
        "role_at_algorithmiq": "CCO",
    },
    {
        "name": "Ed Durkin",
        "title": "Chief Financial Officer",
        "linkedin": "https://www.linkedin.com/in/ed-durkin-36362a24/",
        "academic_background": {"highest_degree": "MBA", "field": "Finance", "institutions": [], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": [],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["Financial operations through rapid growth phase"],
        "role_at_algorithmiq": "CFO",
    },
    {
        "name": "Dean Bogdanovic",
        "title": "SVP Engineering",
        "linkedin": "https://www.linkedin.com/in/dbogdanovic/",
        "academic_background": {"highest_degree": "MS/PhD", "field": "Computer Science/Engineering", "institutions": [], "graduation_year": ""},
        "previous_experience": [],
        "research_focus": ["Quantum Control Systems", "Classical-Quantum Interface"],
        "publications_highlights": [],
        "h_index_estimate": 0,
        "notable_achievements": ["Leads classical control systems for neutral-atom quantum computers"],
        "role_at_algorithmiq": "SVP Engineering",
    },
]

conn = sqlite3.connect("profiles.db")
conn.execute(
    "UPDATE competitor_profiles SET key_people=? WHERE id=2",
    (json.dumps(key_people, ensure_ascii=False),),
)
conn.commit()
conn.close()
print(f"Updated {len(key_people)} people")
